export const apartments = [
  {
    id: 1,
    title: 'Apartment1',
    description: 'Apartment1 description',
    price: 345,
    raiting: 4,
    imgSrc: '/images/apartments/Aparment1.jpg',
    location: { city: 'Kharkiv' },
    owner: {
      name: 'Helen',
      phone: '54637829023',
      email: 'Helen@mail.com',
    },
  },
  {
    id: 2,
    title: 'Apartment2',
    description: 'Apartment2 description',
    price: 546,
    raiting: 3,
    imgSrc: '/images/apartments/Aparment2.jpg',
    location: { city: 'Odessa' },
    owner: {
      name: 'Mark',
      phone: '4356729023',
      email: 'Mark@mail.com',
    },
  },
  {
    id: 3,
    title: 'Apartment3',
    description: 'Apartment3 description nflmdsf ,sdsdf gnsld kdfnmlgd sfmmksdfj',
    price: 756,
    raiting: 3.5,
    imgSrc: '/images/apartments/Aparment3.jpg',
    location: { city: 'Odessa' },
    owner: {
      name: 'John',
      phone: '4356729023',
      email: 'John@mail.com',
    },
  },
  {
    id: 4,
    title: 'Apartment4',
    description: 'Apartment4 description',
    price: 965,
    raiting: 4.5,
    imgSrc: '/images/apartments/Aparment4.jpg',
    location: { city: 'Kyiv' },
    owner: {
      name: 'Jaroslav',
      phone: '4356729023',
      email: 'Jaroslav@mail.com',
    },
  },
  {
    id: 5,
    title: 'Apartment5',
    description: 'Apartment5 description',
    price: 1145,
    raiting: 5,
    imgSrc: '/images/apartments/Aparment5.jpg',
    location: { city: 'Kharkiv' },
    owner: {
      name: 'Helen',
      phone: '54637829023',
      email: 'Helen@mail.com',
    },
  },
  {
    id: 6,
    title: 'Apartment2',
    description: 'Apartment6 description',
    price: 546,
    raiting: 3,
    imgSrc: '/images/apartments/Aparment6.jpg',
    location: { city: 'Odesa' },
    owner: {
      name: 'Mark',
      phone: '4356729023',
      email: 'Mark@mail.com',
    },
  },
  {
    id: 7,
    title: 'Apartment3',
    description: 'Apartment7 description',
    price: 556,
    raiting: 3.5,
    imgSrc: '/images/apartments/Aparment7.jpg',
    location: { city: 'Odesa' },
    owner: {
      name: 'John',
      phone: '4356729023',
      email: 'John@mail.com',
    },
  },
  {
    id: 8,
    title: 'Apartment4',
    description: 'Apartment8 description',
    price: 565,
    raiting: 4.5,
    imgSrc: '/images/apartments/Aparment8.jpg',
    location: { city: 'Kyiv' },
    owner: {
      name: 'Jaroslav',
      phone: '4356729023',
      email: 'Jaroslav@mail.com',
    },
  },
];
