const MAX_LENGTH_REVIEW_TO_SHOW = 140;
const REVIEWS_LIMIT = 2;

const STYLE = { COLORS: { MAIN_COLOR: '#ff662d' }, SIZE: { PAGE_LOADER_SIZE: '200px' } };
export { MAX_LENGTH_REVIEW_TO_SHOW, REVIEWS_LIMIT, STYLE };
